In [2]:
import tensorflow as tf
x1=tf.constant([1,2,3,4])
x2=tf.constant([5,6,7,8])
result=tf.multiply(x1,x2)
print(result)

tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)


In [3]:
import tensorflow as tf
a=tf.constant([[7,9,10,5],[2,4,6,8]])
b=tf.constant([[6,4,9,4,],[2,4,6,8]])
result=tf.add(a,b)
print(result)

tf.Tensor(
[[13 13 19  9]
 [ 4  8 12 16]], shape=(2, 4), dtype=int32)


In [4]:
import tensorflow as tf
a=tf.constant([[1,2,3,4,],[2,4,6,8]])
b=tf.constant([[1,4,3,5,],[2,9,6,5]])
result=tf.subtract(a,b)
print(result)

tf.Tensor(
[[ 0 -2  0 -1]
 [ 0 -5  0  3]], shape=(2, 4), dtype=int32)


In [5]:
import numpy as np
tensor=np.array([1,2,3,4,5])
print(tensor)

[1 2 3 4 5]


In [1]:
import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing
abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])

abalone_train.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.435     0.335   0.110         0.334          0.1355          0.0775   
1   0.585     0.450   0.125         0.874          0.3545          0.2075   
2   0.655     0.510   0.160         1.092          0.3960          0.2825   
3   0.545     0.425   0.125         0.768          0.2940          0.1495   
4   0.545     0.420   0.130         0.879          0.3740          0.1695   

   Shell weight  Age  
0        0.0965    7  
1        0.2250    6  
2        0.3700   14  
3        0.2600   16  
4        0.2300   13